### ISSUE TITLE
alias not configurable

### ISSUE THREAD

**Issue by eaigner** [pulimento/hugo-action#1]
The alias of this action is not configurable, thus the action fails every time with

~~~
Error: Invalid project selection, please verify project alias exists and you have access.
Error: No project active, but project aliases are available.

Run firebase use <alias> with one of these options:
~~~

The `alias` is hardcoded as `alias` into `entrypoint.sh`

**Comment by pulimento** [comment]
Hi,
I've just changed it, so alias it's parametrizable now (see https://github.com/pulimento/github-action-hugo-deploy-to-firebase/commit/d5de0a686a554d317c866b8c7feeb3dbfdfed124)

Feel free to try it. Closing now. Thanks for the report.
